version: '3.5'

services:
     api-rede:
        build: .
        container_name: imageverse-backend-api
        depends_on:
            - db
        restart: always
        environment:
            NODE_ENV: development
            DATABASE_HOST: db
            DATABASE_NAME: imageverse
            DATABASE_USERNAME: postgres
            DATABASE_PASSWORD: postgres
            DATABASE_PORT: 5432
            AWS_REGION: us-east-2
            AWS_IMAGES_BUCKET: bucket.aws.com
            PORT: 8000
            GOOGLE_CLIENT_ID: xxxxxxxxx
            GOOGLE_CLIENT_SECRET: xxxxxxx
            AUTH_WEB_REDIRECT: http://localhost:3000
            AUTH_WEB_DOMAIN: localhost:3000
            COOKIE_KEY: secret
            JWT_SECRET: secret
        ports:
            - '8000:8000'
        command: 'node /home/node/app/app.js'
     db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_DB: imageverse
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        ports:
            - '5432:5432'
        volumes:
            - imageverse_bd:/data/postgres

volumes:
    imageverse_bd: {}
